### ISSUE TITLE
Standard Mode Misaligned

### ISSUE THREAD

**Issue by apearson** [andrewpe/goodlock-color-picker#11]
Noted [here](https://github.com/andrewpe/goodlock-hex2color/issues/7#issuecomment-251798191)

**Comment by apearson** [comment]
Someone should go back and make sure Condensed mode is aligned properly.

**Comment by apearson** [comment]
Idea from betatester: 

> did you try to superimpose Standard color picker screenshot with reduced opacity over the Condensed one to see if there's an uneven X Y axes shift?

**Comment by apearson** [comment]
@blindingstars  
We should retest.  I just tried both #000000 and #464646 on my phone and got a perfect match

**Comment by scottalbany** [comment]
@andrewpe - this is seekweb from reddit -- thanks for the invite! I'll take a look at this issue as well, but please note that I'm traveling today and Friday for work. Thanks again! - Scott

**Comment by stephymiehle** [comment]
Still off for me; the following should be #000000; still yielding #070707.

![image](https://cloud.githubusercontent.com/assets/6765732/19159103/d24c5292-8bb0-11e6-87a7-159bd2c7506a.png)

**Comment by apearson** [comment]
I see what the problem is but I can't replicate it on my device. I feel like the standard display on the edge is different from the standard display on the flat.  If there is a way to get on a screen sharing session going we can get this problem worked out.

**Comment by stephymiehle** [comment]
Not a bad idea! I'm unfortunately going to be traveling and occupied tomorrow and over the weekend, but I'd be happy to screenshare on Monday. I work from home, so super-flexible as long as it's not from 10-10:30a Central.

**Comment by apearson** [comment]
Sounds good! There's no way you could get me a full size screenshot and the output of the program when you use #000000 is there?

**Comment by stephymiehle** [comment]
Here's the full-size! I can get you the output once I'm back in for the evening.

![screenshot_20161006-103400](https://cloud.githubusercontent.com/assets/6765732/19170878/b4c1c368-8bdf-11e6-9ea4-ed1556e48bfe.png)

**Comment by stephymiehle** [comment]
```
python hex2goodlock.py "#464646"
Input Hex: #464646
HSV
(0.0, 0.0, 0.27450980392156865)
Display Mode: Condensed
Hue Screen Location: 860x924
Saturation Screen Location: 249px
Value Screen Location: 1262px
adb shell input tap 860 924 && adb shell input tap 249 1262

python hex2goodlock.py "#464646"
Input Hex: #464646
HSV
(0.0, 0.0, 0.27450980392156865)
Display Mode: Condensed
Hue Screen Location: 860x924
Saturation Screen Location: 249px
Value Screen Location: 1262px
adb shell input tap 860 924 && adb shell input tap 249 1262
```

is the output. I noticed that it is saying my display mode is condensed, which is incorrect.

**Comment by apearson** [comment]
Thanks @blindingstars that put me on the right track.  I believe it was the screen type detection method I was using.  I've upgrade the detection method to be a little bit smarter in d39440e9c283d554194715aece46044cbc1d47d4!

**Comment by apearson** [comment]
Tests from other beta testers seem promising! It sounds like this commit fixed the problem.  @blindingstars once you test on your device then we'll close this issue.

**Comment by stephymiehle** [comment]
:boom: Works perfectly now with every color I've tossed at it! Nicely done!

**Comment by apearson** [comment]
Perfect!
